import meetBelen from "../assets/meetBelen.png";
import meetNicole from "../assets/meetNicole.png";
import meetNicolas from "../assets/meetNicolas.png";
import meetBelenLarge from "../assets/meetBelenLarge.png";
import meetNicoleLarge from "../assets/meetNicoleLarge.png";
import meetNicolasLarge from "../assets/meetNicolasLarge.png";
import celebration from "../assets/celebration.png";

let pages = [
  //Seccion inicial
  {
    number: 0,
    title: "Social Media Lab",
    video: true,
    meet: false,
    resume: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/DGm127uh4Bs",
    meetName: "Belén",
    documentName:"",

  },

  //Seccion 1/////////////////////////////////////////////////////////////
  {
    number: 1,
    title: "Cimientos de marca",
    video: false,
    meet: true,
    resume: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },
  //----------------- 4 videos
  {
    number: 2,
    title: "Cimientos de marca personal",
    video: true,
    meet: false,
    resume: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },
  {
    number: 3,
    title: "Referentes",
    video: true,
    meet: false,
    resume: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },
  {
    number: 4,
    title: "Mi marca personal",
    video: true,
    meet: false,
    resume: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },
  {
    number: 5,
    title: "Cimientos de la marca",
    video: true,
    meet: false,
    resume: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },
  //fin videos---------

  {
    number: 6,
    title: "Cimientos de marca",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },
  {
    number: 7,
    title: "Cimientos de marca",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },

  //Seccion 2
  {
    number: 8,
    title: "Guiones",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
  {
    number: 9,
    title: "Guiones",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
  {
    number: 10,
    title: "Guiones",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
  {
    number: 11,
    title: "Guiones",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
  //----------------- 3 videos
  {
    number: 12,
    title: "Guiones",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
  {
    number: 13,
    title: "Guiones",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
  {
    number: 14,
    title: "Guiones",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
    //----------------- fin
  {
    number: 15,
    title: "Guiones",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },
  {
    number: 16,
    title: "Guiones",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetImageLarge: meetNicoleLarge,
    meetName: "Nicole",
    documentName:"",
  },

  //Seccion 3
  {
    number: 17,
    title: "Grabación de videos",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },
    //----------------- 3 videos
  {
    number: 18,
    title: "Grabación de videos",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },
  {
    number: 19,
    title: "Grabación de videos",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },
  {
    number: 20,
    title: "Grabación de videos",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },
      //----------------- fin
  {
    number: 21,
    title: "Grabación de videos",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },
  {
    number: 22,
    title: "Grabación de videos",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },
  {
    number: 23,
    title: "Grabación de videos",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },

  //Seccion 4
  {
    number: 24,
    title: "Edición",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },

  //Seccion 5
  {
    number: 25,
    title: "Pre - Publicación",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetImageLarge: meetNicolasLarge,
    meetName: "Nicolás",
    documentName:"",
  },
  {
    number: 26,
    title: "Pre - Publicación",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetName: "Nicolás",
    documentName:"",
  },
  {
    number: 27,
    title: "Pre - Publicación",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicole,
    meetName: "Nicole",
    documentName:"",
  },
  {
    number: 28,
    title: "Pre - Publicación",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetNicolas,
    meetName: "Nicolás",
    documentName:"",
  },
  {
    number: 29,
    title: "Pre - Publicación",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetName: "Belén",
    documentName:"",
  },

  //seccion 6
  {
    number: 30,
    title: "Publicación",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },

  //Seccion 7
  {
    number: 31,
    title: "Análisis y optimización",
    video: true,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetName: "Belén",
    documentName:"",
  },
  {
    number: 32,
    title: "Análisis y optimización",
    video: false,
    resume: true,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetImageLarge: meetBelenLarge,
    meetName: "Belén",
    documentName:"",
  },
  {
    number: 33,
    title: "Análisis y optimización",
    video: false,
    resume: false,
    meet: true,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: meetBelen,
    meetName: "Belén",
    documentName:"",
  },
  {
    number: 34,
    title: "¡Terminaste tu recorrido!",
    video: false,
    resume: false,
    meet: false,
    document: false,
    videoSource: "https://www.youtube.com/embed/GUf81ofAZV0",
    resumeText:
      "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum tempora dolorum dignissimos quasi explicabo error asperiores eum nesciunt ducimus quo molestiae totam sunt illum, accusantium quibusdam incidunt temporibus aperiam recusandae illo voluptatibus. Modi, soluta ullam molestias non cumque odio molestiae quia dignissimos fugit magnam eaque officiis, amet suscipit commodi, pariatur dolor! Debitis molestias dolor laboriosam itaque dolore ea autem perferendis voluptatibus libero at!",
    meetImage: celebration,
    meetName: "Belén",
    documentName:"",
  },
];

export default pages;
